version: "3.10"

services:
  app_db:
    container_name: dev-db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.example
  app_django:
    build: .
    working_dir: /django_app
    entrypoint: "sh entrypoint.sh"
    env_file:
      - .env.example
    tty: true
    volumes:
      - .:/django_app
    ports:
      - "8800:8800"
    depends_on:
      - app_db